create main screen
rep-co/fablescope-ios pull request #1
Opened 2023-11-17 14:17 UTC by sergey-aslonyns

добавил главный экран и ассеты для него

2023-11-17 14:29 UTC, LolleyBall requested changes

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +class MainScreenViewController: UIViewController {
final class

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        }
удалить лишний таб

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +
лишняя строка

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +
лишняя строка

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +            buttonStackView.leftAnchor.constraint(equalTo: view.leftAnchor,constant: 20),
ставь энтер между констрейнтами разных сущностей

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +            autoButton.widthAnchor.constraint(equalToConstant: 166),
ставь энтер между констрейнтами разных сущностей

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +            createButton.widthAnchor.constraint(equalToConstant: 166),
не перемешивай констрейнты для разных сущностей

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +
Лишняя строка

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +    func setupButton(){
setupButtons

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +
лишняя строка

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +             autoButton.configure(text: "Авто", image: imageB)
лишний пробел перед autoButton

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +class MenuButton: UIControl {
final class

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +
лишняя строка

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +            label.bottomAnchor.constraint(equalTo: self.bottomAnchor,constant: -20),
энтер между констрейнтами разных сущностей

2023-11-17 14:29 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +
лишняя строка

2023-11-17 18:02 UTC, Mov4D commented
Ветку называем FS-номер задачи_название ветки 
кометы FS-номер задачи: что сделал

2023-11-17 18:12 UTC, Mov4D requested changes

2023-11-17 18:12 UTC, Mov4D commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        buttonStackView.addArrangedSubview(autoButton)
сделать метод addSubviews и addArrangedSubviews
`
view.addSubviews[
    backgroundImageView,
    buttonStackView
]
`

2023-11-17 18:12 UTC, Mov4D commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +            buttonStackView.rightAnchor.constraint(equalTo: view.rightAnchor,constant: -20),
константы выносим в enum Constants

2023-11-17 18:12 UTC, Mov4D commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        buttonStackView.spacing = 20.0
выносим в константы

2023-11-17 18:12 UTC, Mov4D commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        if let imageA = UIImage(named: "magic_wand_icon"),let imageB = UIImage(named: "book_icon") {
```suggestion
        if let imageA = UIImage(named: "magic_wand_icon"), let imageB = UIImage(named: "book_icon") {
```

2023-11-17 18:12 UTC, Mov4D commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        if let imageA = UIImage(named: "magic_wand_icon"),let imageB = UIImage(named: "book_icon") {
Для констант делай нормальные имена - imageA - createImage

2023-11-17 18:12 UTC, Mov4D commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +    let label = UILabel()
нужно делать private

2023-11-17 18:12 UTC, Mov4D commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +        label.numberOfLines = 1
по стандарту и так 1

2023-11-17 18:12 UTC, Mov4D commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +        label.textColor = UIColor.white
```suggestion
        label.textColor = .white
```

2023-11-17 18:19 UTC, tplaymeow requested changes

2023-11-17 18:19 UTC, tplaymeow commented on fablescope/fablescope/AppDelegate.swift
>          // Override point for customization after application launch
Коммент не актуален

2023-11-17 18:19 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +            ])
Неправильный отступ. Используй `Control+I`

2023-11-17 18:19 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +            createButton.configure(text: "Cделай сам", image:imageA)
Добавь пробел перед imageA
```suggestion
            createButton.configure(text: "Cделай сам", image: imageA)
```

2023-11-17 18:19 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        if let imageA = UIImage(named: "magic_wand_icon"),let imageB = UIImage(named: "book_icon") {
imageA, imageB - плохие названия

2023-11-17 18:19 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        if let imageA = UIImage(named: "magic_wand_icon"),let imageB = UIImage(named: "book_icon") {
между `let`-ами добавь либо перенос, либо пробел

2023-11-17 18:19 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +            label.leftAnchor.constraint(equalTo: self.leftAnchor,constant: 10)
Добавь пробел перед ",constant"

2023-11-17 18:19 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +    let label = UILabel()
Почему не `private`?

2023-11-17 18:19 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +    let imageView = UIImageView()
Почему не `private`?

2023-11-17 18:19 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +//  menuButton.swift
Файл называется по-другому

2023-11-17 18:19 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +//  ViewController.swift
Файл называется по-другому

2023-11-17 18:19 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +    func setupButton(){
Пропущен пробел перед "{"

2023-11-17 18:19 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +    func  setupButtonStackView(){
Пропущен пробел перед "{"

2023-11-17 18:25 UTC, tplaymeow requested changes

2023-11-17 18:25 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +    func  setupButtonStackView(){
Лишний пробел поле func

2023-11-17 18:26 UTC, tplaymeow commented
В целом сделано неплохо, но есть пара маленьких замечаний!

2023-11-20 21:10 UTC, tplaymeow requested changes
Стало лучше

2023-11-20 21:10 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        backgroundImageView.image = UIImage(named: "main_screen_background")
Не в константах

2023-11-20 21:10 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/UIImage+.swift
> +    static let bookIcon = UIImage(named: "book_icon")
Форс анврапни!!!

2023-11-20 21:10 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        static let autoButtonConstraint: CGFloat = 166
Названия непонятные. Как понять что это? Высота? Ширина? Отступ?

2023-11-20 21:10 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +            ])
выравние

2023-11-20 21:10 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +        label.font = UIFont(name: "Pacifico-Regular", size: 24)
Вынеси в константы

2023-11-20 21:10 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +        static let leftLabelConstraint: CGFloat = 10
Кривые имена

2023-11-20 21:10 UTC, tplaymeow commented on fablescope/fablescope/UIColor+.swift
> +    static let fableGreen = UIColor(named: "fable_green")
Форс анврапни!!!

2023-11-20 21:10 UTC, tplaymeow commented on fablescope/fablescope/UIColor+.swift
> +extension UIColor{
```suggestion
extension UIColor {
```

2023-11-20 21:11 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +private extension MainScreenViewController {
// MARK: - Private Methods -
как в классе кнопки

2023-11-20 21:11 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        autoButton.backgroundColor = UIColor(named: "fable_green")
надо будет создать задачу - добавить экстеншены к цветам, шрифтам и картинкам, чтобы удобно их вызывать

2023-11-20 21:11 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +        static let leftImageViewConstraint: CGFloat = 53
названия непонятные, слово констрейнт не должно использоваться. Должны быть слова left, tight, top, bottom, width, height - для указания параметра задаваемого. И использоваться слово inset - отступ или любой другой смысл константы.
Далее называй константы так пример: imageView(название вьюхи)Top(указание стороны констрейнта)Inset(отступ или любой другой параметр) . без скобочек это выглядит так  imageViewTopInset

2023-11-21 15:04 UTC, Mov4D approved these changes

2023-11-21 15:09 UTC, LolleyBall requested changes

2023-11-21 15:09 UTC, LolleyBall commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +
лишняя строка

2023-11-21 15:38 UTC, rofle100lvl reviewed
Норм, чутка осталось

2023-11-21 15:38 UTC, rofle100lvl commented on fablescope/fablescope/Extensions/UIFont+.swift
> +    static let  pacificoRegular = UIFont(name: "Pacifico-Regular", size: 24)!
лишний пробел

2023-11-21 15:38 UTC, rofle100lvl commented on fablescope/fablescope/Extensions/UIFont+.swift
> +    static let  pacificoRegular = UIFont(name: "Pacifico-Regular", size: 24)!
И назавание файла еще бы поправить

2023-11-21 15:38 UTC, rofle100lvl commented on fablescope/fablescope/Extensions/UIImage+.swift
> +}
Го в название файла добавим после + что-нибудь

2023-11-21 15:38 UTC, rofle100lvl commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        backgroundImageView.translatesAutoresizingMaskIntoConstraints = false
лишняя строка

2023-11-21 15:38 UTC, rofle100lvl commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        static let buttonStackViewLeftInset: CGFloat = 20
Лайк за подход

2023-11-21 15:39 UTC, rofle100lvl commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        backgroundImageView.translatesAutoresizingMaskIntoConstraints = false
и пробел в названии

2023-11-21 15:39 UTC, rofle100lvl commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        static let buttonStackViewLeftInset: CGFloat = 20
но убери пробел в названии файла

2023-11-21 15:51 UTC, LolleyBall approved these changes

2023-11-21 18:22 UTC, sergey-aslonyns commented on fablescope/fablescope/Extensions/UIImage+.swift
> +}
Там все extensions для UIImage

2023-11-21 18:27 UTC, tplaymeow requested changes

2023-11-21 18:27 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MenuButton.swift
> +        static let ImageViewRightInset: CGFloat = -53
названия с маленькой буквы

2023-11-21 18:36 UTC, tplaymeow requested changes

2023-11-21 18:36 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        static let buttonStackViewHeightInset: CGFloat = 166
HeightInset wtf?

2023-11-21 18:36 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        static let createButtonInset: CGFloat = 166
createButtonInset = 166 wtf?

2023-11-21 18:44 UTC, tplaymeow approved these changes

2023-11-21 19:51 UTC, merged