FSCP-4: Form screen
rep-co/fablescope-ios pull request #3
Opened 2023-12-05 10:52 UTC by sergey-aslonyns

2023-12-11 14:03 UTC, tplaymeow requested changes

2023-12-11 14:03 UTC, tplaymeow commented on .DS_Store
Добавь в gitignore

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Extensions/UIColor+.swift
> +
Удали пустую строку

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Extensions/UIImage+.swift
> +
Удали пустую строку

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +            guard let data = data else { return }
Можно просто guard let data else { return }

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +            if isSelectedCell == false {
if !isSelectedCell

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +                layer.borderColor = UIColor.fableGreen.cgColor
Почему в другой ветке не убираешь это?

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +            NSLayoutConstraint.activate([
Отступов дофига

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        CastomData( image: .witchHat ),
Пробелы перед лейблом у аргумента не нужен

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +            ])
Неправильный отступ

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        }
Слишком сложная конструкция
Модно просто a = !a
Или a.toggle()

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        return CGSize(width: collectionView.frame.width/3.75, height: collectionView.frame.width/3.75)
Что такое 3.75? В коде не должно быть magic numbers

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        return CGSize(width: collectionView.frame.width/3.75, height: collectionView.frame.width/3.75)
Перед и после операторов нужен пробел

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +           return UIEdgeInsets(top: 20, left: 20, bottom: 20, right: 20)
Выравнивания опять сделали брррр. Нажимай ты cmd-i

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +
Удали строку

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/ReadyButton.swift
> +final class ReadyButton: UIControl {
Добавь пробел после import

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +
Удали пустую линию

2023-12-11 14:03 UTC, tplaymeow commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
![image](https://github.com/rep-co/fablescope-ios/assets/35903356/87a5be95-9e5d-415b-80ad-ec42f03f449e)

2023-12-12 09:26 UTC, Mov4D requested changes

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> + import UIKit
лишний пробел перед import

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +    var isSelectedCell: Bool = false {
все что внутри didSet нужно в отдельную функцию вынести

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +
Добавляй комментарии к extension // MARK: - Что ты делаешь внутри

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +        setupConstraints()
Их лучше в init вызывать

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +struct CastomData {
Плохое название + не правильно написано

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +    private let createButton = ReadyButton()
почему экземпляр create а класс Ready?

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +class FromScreenViewController: UIViewController {
final

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        let cv = UICollectionView(frame: .zero, collectionViewLayout: layout)
двумя буквами не называем переменные

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        cv.register(CollectionViewCell.self, forCellWithReuseIdentifier: "cell")
регистрацию ячейки лучше в отдельный метод вынести

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        title = "Выбери все что хочешь"
в SetupUI вынеси

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        addSubwiews()
вызов должен быть из viewDidLoad

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        collectionView.backgroundColor = .white
это явно не в addSubviews должно быть

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        collectionView.dataSource = self
и это

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        setupConstraints()
вызывай из viewDidLoad

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: indexPath) as! CollectionViewCell
forseUnwrap

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        cell.backgroundColor = .fableGreen
ячейку внутри своего класса настраивай

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        return CGSize(width: collectionView.frame.width/3.75, height: collectionView.frame.width/3.75)
Да вынеси в const и дай логичное название

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Form Screen/ReadyButton.swift
> +        setupLabel()
вызов этих функций должен быть явно не здесь

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +    @objc func onClick() {
плохое название не понятно на что именно нажали лучше didTapCreateButton

2023-12-12 09:26 UTC, Mov4D commented on fablescope/fablescope/Main Screen/MainScreenViewController.swift
> +        navigationController?.pushViewController(FromScreenViewController(), animated: true)
Навигация должна быть через Router, посмотри MVC + Router

2023-12-12 10:12 UTC, Mov4D commented
грязный код

2023-12-12 15:29 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +    var data: CastomData? {
CustomData*

2023-12-12 15:29 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +           return UIEdgeInsets(top: 20, left: 20, bottom: 20, right: 20)
пожалуйста

2023-12-12 15:29 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/ReadyButton.swift
> +            label.rightAnchor.constraint(equalTo: self.rightAnchor),
![image](https://github.com/rep-co/fablescope-ios/assets/45801227/5fc3086d-573b-465a-ae8e-bc7e4ad1549e)

2023-12-12 15:30 UTC, rofle100lvl commented
<img width="135" alt="Screenshot 2023-12-12 at 16 30 36" src="https://github.com/rep-co/fablescope-ios/assets/45801227/3c63583a-9082-406c-bc9b-ecf873832d54">
Давай без русского языка в коммитах

2023-12-12 17:11 UTC, tplaymeow requested changes

2023-12-12 17:11 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +class CollectionViewCell: UICollectionViewCell {
CollectionViewCell - странное название. Название класса должно отражать его назначение. Это же не просто какая-то случайная ячейка, это ячейка, которая отражает конкретные данные

2023-12-12 17:11 UTC, tplaymeow commented on fablescope/fablescope/AppDelegate.swift
>          // Override point for customization after application launch
Так и не исправил комментарий, который я просил убрать еще в прошлом пр-е. УДОЛИ ЕГО!!!

2023-12-12 17:11 UTC, tplaymeow commented on fablescope/fablescope/Extensions/UIColor+.swift
> +    static let frostColor = UIColor(named: "frost_color")!
Почему именно такие названия у цветов?

2023-12-12 17:11 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +class CollectionViewCell: UICollectionViewCell {
Сделай класс final

2023-12-12 17:11 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +        didSet{
добавь пробел перед фигурной скобкой

2023-12-12 17:11 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +       let iv = UIImageView()
iv - плохое название, напиши imageView

2023-12-12 17:11 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +    required init?(coder : NSCoder) {
Удали пробел перед двоеточием

2023-12-13 14:20 UTC, Mov4D requested changes

2023-12-13 14:20 UTC, Mov4D commented on fablescope/fablescope/Extensions/UIImage+.swift
> -// swiftlint:disable force_unwrap
Зачем эту строчку убрал?

2023-12-13 14:20 UTC, Mov4D commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
>      private let  cellImage: UIImageView = {
2 пробела

2023-12-13 14:20 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +struct ViewModel {
структура ViewModel не должна лежать просто в воздухе

2023-12-13 14:20 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        static let collectionViewrRatio: CGFloat = 3.75
неверно написано

2023-12-14 17:26 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        ViewModel( image: .witchHat ),
Убери лишние пробелы плиз

2023-12-14 17:26 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +final class FromScreenViewController: UIViewController {
Так "FormScreen" или "FromScreen"?

2023-12-14 17:26 UTC, tplaymeow commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +    func addSubwiews() {
Очепятка addSubviews

2023-12-25 10:29 UTC, tplaymeow approved these changes
Круто! Отдай в тестирование

2024-02-15 09:47 UTC, Mov4D requested changes

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Fairy Tale Screen/FairyTaleScreenController.swift
> +class FairyTaleScreenController: UIViewController {
```suggestion
import UIKit

final class FairyTaleScreenController: UIViewController {
```

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Fairy Tale Screen/FairyTaleScreenController.swift
> +    let  scrollView1 = UIView()
неверный уровень доступа

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +    var data = [
почему не private?

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +    ]
```suggestion
    ]
    
```

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +private extension FormScreenViewController{
```suggestion
private extension FormScreenViewController {
```

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +    func setupCollectionView(){
```suggestion
    func setupCollectionView() {
```

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        title = "Выбери все что хочешь"
в конст вынеси

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        collectionView.backgroundColor = .white
почему это в addSubviews?

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        navigationController?.navigationBar.titleTextAttributes = [
почему это в addSubviews?

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: indexPath) as! CollectionViewCell
избавься от !

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +        data[indexPath.row] = .init(image: data[indexPath.row].image, isSelected:  !data[indexPath.row].isSelected)
Что если по этому индексу не будет элемента?

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +    }
Сделай норм переносы

2024-02-15 09:47 UTC, Mov4D commented on fablescope/fablescope/Form Screen/SubmitButton.swift
> +    private let label = UILabel()
плохое название

2024-02-18 11:20 UTC, rofle100lvl submitted a review, later dismissed

2024-02-18 11:20 UTC, rofle100lvl commented on fablescope/fablescope/Fairy Tale Screen/FairyTaleScreenController.swift
> +    private let skrollView = UIScrollView()
scroll

2024-02-18 11:20 UTC, rofle100lvl commented on fablescope/fablescope/Fairy Tale Screen/FairyTaleScreenController.swift
> +    private let  scrollView1 = UIView()
название scrollView1 ни о чем не говорит, и почему в переменной scrollView лежит UIView? + пробел лишний

2024-02-18 11:20 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +
строка лишняя

2024-02-18 11:20 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +            setupDidSet()
название непонятное  переименуй во что-то типа onCellSelection или что-нибудь такое

2024-02-18 11:20 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +    private let  cellImage: UIImageView = {
пробел лишний

2024-02-18 11:20 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +
строка лишняя

2024-02-18 11:20 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/CollectionViewCell.swift
> +    func setupConstraints() {
лайк, что методы повыносил

2024-02-18 11:20 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +
строка лишняя

2024-02-18 11:20 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +
строка лишняя

2024-02-18 11:20 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +
строка лишняя

2024-02-18 11:20 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/FormScreenViewController.swift
> +
тут тоже

2024-02-18 11:20 UTC, rofle100lvl commented on fablescope/fablescope/Form Screen/SubmitButton.swift
> +
и тут

2024-02-18 11:21 UTC, rofle100lvl commented
PR становится слишком большим, ничего нового сюда больше не добавляй. Доисправляй комменты и вливаем

2024-02-22 10:57 UTC, Mov4D approved these changes

2024-02-22 10:58 UTC, rofle100lvl commented
жоска ты меня отшил

2024-02-22 11:03 UTC, merged